# Generated by Django 3.1.6 on 2021-10-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('x_KMA', models.IntegerField()),
                ('y_KMA', models.IntegerField()),
                ('KMA_UltraSrtFcst_updated_at', models.DateTimeField(blank=True, null=True)),
                ('KMA_SrtFcst_updated_at', models.DateTimeField(blank=True, null=True)),
                ('VC_MtFcst_updated_at', models.DateTimeField(blank=True, null=True)),
                ('OWM_AirPollution_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FutureBikeStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField()),
                ('predicted_parking_bike_count', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(db_column='station', on_delete=django.db.models.deletion.CASCADE, to='maps.bikestation', to_field='station_num')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField()),
                ('weather_source', models.IntegerField(blank=True, choices=[(1, 'KMA_UltraSrtFcst'), (2, 'KMA_SrtFcst'), (3, 'VC_MtFcst')], null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('precipitation_prob', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pm10', models.IntegerField(blank=True, choices=[(1, 'Good'), (2, 'Moderate'), (3, 'Bad'), (4, 'Very Bad')], null=True)),
                ('pm2_5', models.IntegerField(blank=True, choices=[(1, 'Good'), (2, 'Moderate'), (3, 'Bad'), (4, 'Very Bad')], null=True)),
                ('ozone', models.IntegerField(blank=True, choices=[(1, 'Good'), (2, 'Moderate'), (3, 'Bad'), (4, 'Very Bad')], null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.area')),
            ],
        ),
        migrations.AddConstraint(
            model_name='futurebikestation',
            constraint=models.UniqueConstraint(fields=('station', 'prediction_time'), name='prediction_time unique for station'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('area', 'forecast_time'), name='forecast_time unique for area'),
        ),
    ]
